<h1>Artists</h1>
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach($this->artists['_embedded']['artist'] as $artist) { ?>
    <tr>
      <td><a href="<?= $artist['_links']['self']['href']; ?>"><?= $artist['id']; ?></a></td>
      <td><?= $artist['name']; ?></td>
    </tr>
  <?php } ?>
  </tbody>
</table>
<?php
var_dump($this->artists['_embedded']['artist'][0]);
?>