<?php if ($this->pageCount) { ?>
	<div class="paginationControl">
		<!-- Previous page link -->
		<?php if (isset($this->previous)) { ?>
			<a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">< Previous</a> |
		<?php } else { ?>
			<span class="disabled">< Previous</span> |
		<?php } ?>

		<!-- Numbered page links -->
		<?php foreach ($this->pagesInRange as $page) { ?>
			<?php if ($page != $this->current) { ?>
				<a href="<?php echo $this->url($this->route, ['page' => $page]); ?>"><?php echo $page; ?></a> |
			<?php } else { ?>
				<?php echo $page; ?> |
			<?php } ?>
		<?php } ?>

		<!-- Next page link -->
		<?php if (isset($this->next)) { ?>
			<a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">Next ></a>
		<?php } else { ?>
			<span class="disabled">Next ></span>
		<?php } ?>
	</div>
<?php } ?>